/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numbers;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class NumberTrackerTest {
    @Test void detectsDuplicates() {
        // Assemble
        String duplicateNumber = "000111222";
        String nonDuplicatedNumber = "333444555";
        NumberTracker tracker = new NumberTracker();
        tracker.trackDuplicate(duplicateNumber);

        // Act
        boolean resultNotDuplicated = tracker.trackDuplicate(nonDuplicatedNumber);
        boolean resultDuplicated = tracker.trackDuplicate(duplicateNumber);
        
        // Assert
        assertFalse(resultNotDuplicated, nonDuplicatedNumber + "should not be a duplicate");
        assertTrue(resultDuplicated, duplicateNumber + "should be a duplicate");
    }

    @Test void tracksStats() {
        // Assemble
        NumberTracker tracker = new NumberTracker();
        // Track 10 unique numbers
        for(int i = 0; i < 10; i++) {
            tracker.trackDuplicate(String.format("00011122%d", i));
        }
        // Track 5 duplicate numbers
        for(int i = 0; i < 5; i++) {
            tracker.trackDuplicate(String.format("00011122%d", i));
        }

        // Act
        Stats result = tracker.resetStats();
        
        // Assert
        assertEquals(10, result.getNewUniques(), "uniques since clear stats");
        assertEquals(5, result.getNewDuplicates(), "duplicates since clear stats");
        assertEquals(10, result.getTotalUniques(), "total numbers");

        // Assemble - cleared stats
        // Track 10 more unique numbers
        for(int i = 0; i < 10; i++) {
            tracker.trackDuplicate(String.format("33344455%d", i));
        }
        // Track 3 duplicate numbers from the prior round
        for(int i = 0; i < 3; i++) {
            tracker.trackDuplicate(String.format("00011122%d", i));
        }
        // Track 2 duplicate numbers from the new round
        for(int i = 0; i < 2; i++) {
            tracker.trackDuplicate(String.format("33344455%d", i));
        }

        // Act
        result = tracker.resetStats();
        
        // Assert
        assertEquals(10, result.getNewUniques(), "uniques since clear stats");
        assertEquals(5, result.getNewDuplicates(), "duplicates since clear stats");
        assertEquals(20, result.getTotalUniques(), "total numbers");
    }
}
